# Generated by Django 3.2.8 on 2021-10-19 04:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partidas', '0002_solicitud'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitud',
            unique_together={('partida', 'usuario')},
        ),
    ]
