# Generated by Django 3.2.8 on 2021-10-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0003_alter_solicitud_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='is_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
